import { configure } from '@storybook/vue'

import Vue from 'vue'

import '../src/storybook/global/_global.scss'

import ElementUI from 'element-ui'
import lang from 'element-ui/lib/locale/lang/ru-RU'
import locale from 'element-ui/lib/locale'

import '../src/main.scss'
import '../src/components/base.scss'
import '../src/components/pagination.scss'
import '../src/components/dialog.scss'
import '../src/components/autocomplete.scss'
import '../src/components/dropdown.scss'
import '../src/components/dropdown-menu.scss'
import '../src/components/dropdown-item.scss'
import '../src/components/menu.scss'
import '../src/components/submenu.scss'
import '../src/components/menu-item.scss'
import '../src/components/menu-item-group.scss'
import '../src/components/input.scss'
import '../src/components/input-number.scss'
import '../src/components/radio.scss'
import '../src/components/radio-group.scss'
import '../src/components/radio-button.scss'
import '../src/components/checkbox.scss'
import '../src/components/checkbox-button.scss'
import '../src/components/checkbox-group.scss'
import '../src/components/switch.scss'
import '../src/components/select.scss'
import '../src/components/button.scss'
import '../src/components/button-group.scss'
import '../src/components/table.scss'
import '../src/components/table-column.scss'
import '../src/components/date-picker.scss'
import '../src/components/time-select.scss'
import '../src/components/time-picker.scss'
import '../src/components/popover.scss'
import '../src/components/tooltip.scss'
import '../src/components/message-box.scss'
import '../src/components/breadcrumb.scss'
import '../src/components/breadcrumb-item.scss'
import '../src/components/form.scss'
import '../src/components/form-item.scss'
import '../src/components/tabs.scss'
import '../src/components/tab-pane.scss'
import '../src/components/tag.scss'
import '../src/components/tree.scss'
import '../src/components/alert.scss'
import '../src/components/notification.scss'
import '../src/components/slider.scss'
import '../src/components/loading.scss'
import '../src/components/row.scss'
import '../src/components/col.scss'
import '../src/components/upload.scss'
import '../src/components/progress.scss'
import '../src/components/spinner.scss'
import '../src/components/message.scss'
import '../src/components/badge.scss'
import '../src/components/card.scss'
import '../src/components/rate.scss'
import '../src/components/steps.scss'
import '../src/components/step.scss'
import '../src/components/carousel.scss'
import '../src/components/scrollbar.scss'
import '../src/components/carousel-item.scss'
import '../src/components/collapse.scss'
import '../src/components/collapse-item.scss'
import '../src/components/cascader.scss'
import '../src/components/color-picker.scss'
import '../src/components/transfer.scss'
import '../src/components/container.scss'
import '../src/components/header.scss'
import '../src/components/aside.scss'
import '../src/components/main.scss'
import '../src/components/footer.scss'
import '../src/components/cascader-panel.scss'

locale.use(lang)
Vue.use(ElementUI)

configure(require.context('../src', true, /\.stories\.js$/), module)
